Update trivy-sbom.yaml

diff --git a/.github/workflows/trivy-sbom.yaml b/.github/workflows/trivy-sbom.yaml
--- a/.github/workflows/trivy-sbom.yaml
+++ b/.github/workflows/trivy-sbom.yaml
@@ -54,36 +54,58 @@ jobs:
           TRIVY_PASSWORD: ${{ secrets.AQUASEC_REGISTRY_PASSWORD }}
           AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
           CSPM_URL: https://eu-1.api.cloudsploit.com 
-      - name: Generate SBOM Locally
-        id: generate-sbom-local
-        run: |
-              export BILLY_SERVER=https://billy.codesec.aquasec.com
-              curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-              curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-              if ! cat install.sh.checksum | sha256sum --check; then
-              echo "install.sh checksum failed"
-              exit 1
-              fi
-              BINDIR="." sh install.sh
-              rm install.sh install.sh.checksum
-              ./billy health \
-               --access-token "${{ secrets.GITHUB_TOKEN }}" \
-               --aqua-key "${{ secrets.AQUA_KEY }}" \
-               --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-               --cspm-url https://eu-1.api.cloudsploit.com \
-               --artifact-path "." 
-              ./billy health \
-               --access-token "${{ secrets.GITHUB_TOKEN }}" \
-               --aqua-key "${{ secrets.AQUA_KEY }}" \
-               --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-               --cspm-url https://eu-1.api.cloudsploit.com \
-               --artifact-path "." 
+      # - name: Generate SBOM Locally
+      #   id: generate-sbom-local
+      #   run: |
+      #         export BILLY_SERVER=https://billy.codesec.aquasec.com
+      #         curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+      #         curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+      #         if ! cat install.sh.checksum | sha256sum --check; then
+      #         echo "install.sh checksum failed"
+      #         exit 1
+      #         fi
+      #         BINDIR="." sh install.sh
+      #         rm install.sh install.sh.checksum
+      #         ./billy health \
+      #          --access-token "${{ secrets.GITHUB_TOKEN }}" \
+      #          --aqua-key "${{ secrets.AQUA_KEY }}" \
+      #          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+      #          --cspm-url https://eu-1.api.cloudsploit.com \
+      #          --artifact-path "." 
+      #         ./billy health \
+      #          --access-token "${{ secrets.GITHUB_TOKEN }}" \
+      #          --aqua-key "${{ secrets.AQUA_KEY }}" \
+      #          --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+      #          --cspm-url https://eu-1.api.cloudsploit.com \
+      #          --artifact-path "." 
 
-                # The docker image name:tag of the newly built image
-                # --artifact-path "my-image-name:${{ env.tag-version }}" 
-                # OR the path to the root folder of your project. I.e my-repo/my-app 
-                # --artifact-path "${{env.MY_APP_ROOT}}"
-        env:
-          AQUA_KEY: ${{ secrets.AQUASEC_API_KEY }}
-          AQUA_SECRET: ${{ secrets.AQUASEC_API_SECRET }}
-          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+      #           # The docker image name:tag of the newly built image
+      #           # --artifact-path "my-image-name:${{ env.tag-version }}" 
+      #           # OR the path to the root folder of your project. I.e my-repo/my-app 
+      #           # --artifact-path "${{env.MY_APP_ROOT}}"
+      #   env:
+      #     AQUA_KEY: ${{ secrets.AQUASEC_API_KEY }}
+      #     AQUA_SECRET: ${{ secrets.AQUASEC_API_SECRET }}
+      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
+      - name: Manifest Generation
+        run: |
+          export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key WyKzqHQpnmO5tohpf3zcfy \
+            --aqua-secret ZOpr71Eu4ubcMXaulFWM2O97IVH856GNq2h \
+            --cspm-url https://eu-1.api.cloudsploit.com \
+            --artifact-path . 
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
